## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [3]:
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [4]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [5]:
#split test size into the portion of 0.33 of the whole samples
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
print(X_test)
print(y_test)

[[475 476 477 478 479]
 [ 75  76  77  78  79]
 [150 151 152 153 154]
 [790 791 792 793 794]
 [640 641 642 643 644]
 [575 576 577 578 579]
 [345 346 347 348 349]
 [850 851 852 853 854]
 [870 871 872 873 874]
 [225 226 227 228 229]
 [330 331 332 333 334]
 [910 911 912 913 914]
 [825 826 827 828 829]
 [390 391 392 393 394]
 [930 931 932 933 934]
 [885 886 887 888 889]
 [280 281 282 283 284]
 [760 761 762 763 764]
 [410 411 412 413 414]
 [340 341 342 343 344]
 [620 621 622 623 624]
 [ 80  81  82  83  84]
 [740 741 742 743 744]
 [465 466 467 468 469]
 [325 326 327 328 329]
 [300 301 302 303 304]
 [420 421 422 423 424]
 [335 336 337 338 339]
 [625 626 627 628 629]
 [660 661 662 663 664]
 [ 45  46  47  48  49]
 [ 90  91  92  93  94]
 [275 276 277 278 279]
 [375 376 377 378 379]
 [750 751 752 753 754]
 [520 521 522 523 524]
 [675 676 677 678 679]
 [685 686 687 688 689]
 [820 821 822 823 824]
 [380 381 382 383 384]
 [395 396 397 398 399]
 [985 986 987 988 989]
 [190 191 192 193 194]
 [120 121 1

In [12]:
#METHOD 1(針對不同類別各自作切分後再合併)
y1, y0 = train_test_split(y, test_size=160, random_state=42, shuffle = False)
print(y1)
y1_train, y1_test = train_test_split(y1, test_size=10, random_state=42, shuffle = False)
print(y1_test)
y0_train, y0_test = train_test_split(y0, test_size=10, random_state=42, shuffle = False)
print(y0_test)
y_test = np.concatenate((y1_test, y0_test))
y_train = np.concatenate((y1_train, y0_train))
print(y_test)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [14]:
#METHOD 2
for i in range(500):
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=i)
    (i, y_test)
    Sum =sum(y_test)
    if Sum == 10:
        print ("Random _State =",i, y_test, "y_test 中能各有 10 筆類別 0 與 10 筆類別 1")

Random _State = 497 [0. 0. 0. 1. 0. 0. 0. 1. 1. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 1.] y_test 中能各有 10 筆類別 0 與 10 筆類別 1
